import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFC12F);
const kRedColor = Color(0xCCC70039);
const kSecondaryColor = Color(0xFFFFE6AC);
const kGoldColor = Color(0xDDD4AF37);
const kUnActiveColor = Color(0xFFC1BDB8);
const kGrenColor = Color.fromARGB(33,150,243,1);
const kMoveColor = Color(0xff7f00ff);
const kMovliColor = Color(0xffe100ff);
const kJackets = 'jackets';
const kTrousers = 'trousers';
const kTshirts = 't-shirts';
const kShoes = 'shoes';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';